---
- name: NVM | Create NVM_DIR
  file:
    path: ~/.nvm
    state: directory

- name: NVM | Install NVM
  shell: curl https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  args:
    creates: "{{ home_path }}/.nvm/nvm.sh"
  become: yes

- name: NVM | Enable NVM in .zshrc
  blockinfile:
    path: "{{ home_path }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK #"
    content: "{{ load_nvm_command }}"