---
- name: Install VSCode PHP Extensions
  command: "{{ vscode_path }} --install-extension '{{ item }}' --force"
  with_items: "{{ vscode_php_extensions }}"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
